### ISSUE TITLE
แจ้งเตือนแก้ไข บรรทัดโค้ด ที่ 217 กับ 219 เรื่อง size เพื่อจะได้ใช้ jq version ใหม่ ได้ (ไฟล์ bootstrap-datepicker.js)

### ISSUE THREAD

**Issue by benzzamakon** [jojosati/bootstrap-datepicker-thai#3]
จาก
this.element.is(e.target) ||
this.element.find(e.target).size() ||
this.picker.is(e.target) ||
this.picker.find(e.target).size() 
เป็น 
this.element.is(e.target) ||
this.element.find(e.target).length ||
this.picker.is(e.target) ||
this.picker.find(e.target).length
# size กับ length สามารถใช้ได้เหมือนกัน 
#สำหรับคนที่เจอ ERROR ตรงบรรทัดนี้ ปัญหาเกิดจากการเปลี่ยน version jq นะ ครับ ด้วยความ หวังดีจาก  programer คนหนึ่ง ครับ

**Comment by jojosati** [comment]
@benzzamakon ขอบคุณครับ

1. ตรวจสอบกับ [ต้นฉบับ ของ uxsolutions](https://github.com/uxsolutions/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L439)  เห็นว่าเปลี่ยนไปใช้ `.length` ตามที่แจ้ง

2. ตรวจสอบ [jquery api](https://api.jquery.com/size/#size) แล้ว `.size()` เอาออกตั้งแต่ v.3.0

3. ผม patch ให้ใช้ได้ทั้ง jq < 3 และ jq >= 3 แล้วนะครับ
```
[$(document), {
	mousedown: $.proxy(function (e) {
		// Clicked outside the datepicker, hide it
	       var _size = function (o) {
		    return o.length || (o.size && o.size());
		}
		if (!(
			this.element.is(e.target) ||
			_size(this.element.find(e.target)) ||
			this.picker.is(e.target) ||
			_size(this.picker.find(e.target))
		)) {
			this.hide();
		}
	}, this)
}]
```
พอดี code นี้ ตั้งแต่ทำมาแล้วไม่เคยใช้ใน project ตัวเองเลย
ถ้าต้องการให้ปรับปรุงอะไร ก็ส่ง PR มาได้นะครับ
หรือถ้าต้องการเอาไปดูแลแทน ก็ fork แล้วแจ้งมาได้นะครับ
ผมได้ update ให้ใน readme

**Comment by jojosati** [comment]
https://github.com/jojosati/bootstrap-datepicker-thai/commit/262f6c89f4588d7dcbf8fa8616a65591bc97c853
